// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAGgmJme7uNYTGekBVl8MXg64-fDHkmU',
    appId: '1:286790954704:web:03a69fccc5839acc6578d5',
    messagingSenderId: '286790954704',
    projectId: 'appointmentbookingcorrect',
    authDomain: 'appointmentbookingcorrect.firebaseapp.com',
    storageBucket: 'appointmentbookingcorrect.appspot.com',
    measurementId: 'G-CN2B8M8FDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj40DQ8UAYiYfMnK0TFtLgNWJvlTfbsfY',
    appId: '1:286790954704:android:6c9ec7b6ba6003dd6578d5',
    messagingSenderId: '286790954704',
    projectId: 'appointmentbookingcorrect',
    storageBucket: 'appointmentbookingcorrect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARMaZCxmYtZSmjB6l-kqlU-UGjStUd8_0',
    appId: '1:286790954704:ios:18383dd75196e08b6578d5',
    messagingSenderId: '286790954704',
    projectId: 'appointmentbookingcorrect',
    storageBucket: 'appointmentbookingcorrect.appspot.com',
    iosBundleId: 'com.example.responsivetutorial',
  );
}
